### PR TITLE
updated location_table and added district shapefile

### PR DESCRIPTION
**Pull request by d-hergott**
Updated location table added from an API call on 08MAY2024. Added in a district shapefile for Uganda with geometries that are valid and align with the IDs in the loc_table to be used for plotting.

### CODE REVIEW

**Comment by aucarter** [comment]
A couple questions... what are the `emonc` and `emonc_unsupported_and_cross_cutting` columns in the `loc_table`? When I load the library and try to plot the shapefile i get the following error:
`> plot(uga_district_shp)
Error in data.matrix(x) : 
  'list' object cannot be coerced to type 'double'`
  
Is that unusual? I feel like I remember being able to plot shapefile.

**Comment by d-hergott** [comment]
hmm...I did not add those `emonc` columns myself- they were in the file that you downloaded (I just copy and pasted it into the file and changed the name- I did not manipulation for this). 

For the shapefile- you should be able to plot it. When I load it in outside of this package, I have no issues.  Can you verify what the structure of the file is?

**Comment by aucarter** [comment]
Ok, i don't really see where those columns were made in constructing the initial location table. Is [this](https://github.com/dd-harp/uga-etl-spatial-hierarchy/blob/1-investigate-shapefile-and-location-table-for-consistency/prep_loc_table.R) the script that generated the location table used here?

image

**Comment by aucarter** [comment]
I think we should just get rid of the `emonc` columns but I am curious where they came from

**Comment by d-hergott** [comment]
Yes- that seems to be the code. I pulled in your file C:\Users\dhergott\Box\RAMP\Scratch\Austin\240508_location_hierarchy.csv which was made for that. 

I'm fine deleting them!

Odd on the shapepfile. When I just load it in outside of the package, the geometries are not as a list. Are they pulled in just using `load`, or is there another way the .rda files are loaded in the package?

**Comment by d-hergott** [comment]
Made a new issue for adding in the dependency and am merging this per discussion with Austin.

**Pull request merged**
